CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;

CREATE TABLE EMP(EMPNO INT, ENAME VARCHAR(10), SAL INT, DEPTNO INT, JOB CHAR, MGR INT);

INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO, JOB, MGR)
VALUES	(1, 'ARUN', 8000, 1, 'M', 4),
		(2, 'ALI', 7000, 1, 'C', 1),
		(3, 'KIRUN', 3000, 1, 'C', 1),
		(4, 'JACK', 9000, 2, 'M', NULL),
		(5, 'THOMAS', 8000, 2, 'C', 4);

CREATE TABLE DEPT(DEPTNO INT, DNAME VARCHAR(10), LOCATION VARCHAR(10));

INSERT INTO DEPT(DEPTNO, DNAME, LOCATION)
VALUES	(1, 'TRN', 'BBY'),
		(2, 'EXP', 'DLH'),
		(3, 'MKTG', 'CAL');

-- JOINS
SELECT ENAME, DNAME 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;
-- DEPT : DRIVING TABLE, EMP : DRIVEN TABLE

-- EQUIJOIN
-- EQUAL CONDITION
SELECT DEPT.DEPTNO, DEPT.DNAME, DEPT.LOCATION, EMP.ENAME, EMP.JOB, EMP.SAL -- GOOD PRACTICE
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO 
ORDER BY 1;

-- INEQUIJOIN
SELECT EMP.ENAME, DEPT.DNAME 
FROM EMP, DEPT
WHERE DEPT.DEPTNO != EMP.DEPTNO;

-- HALF OUTER JOIN

SELECT DEPT.DNAME, EMP.ENAME
FROM EMP RIGHT OUTER JOIN DEPT
ON (DEPT.DEPTNO = EMP.DEPTNO);

SELECT DEPT.DNAME, EMP.ENAME
FROM EMP LEFT OUTER JOIN DEPT
ON (DEPT.DEPTNO = EMP.DEPTNO);

SELECT DEPT.DNAME, EMP.ENAME
FROM EMP INNER JOIN DEPT
ON (DEPT.DEPTNO = EMP.DEPTNO);

SELECT DEPT.DNAME, EMP.ENAME
FROM EMP LEFT OUTER JOIN DEPT
ON (DEPT.DEPTNO = EMP.DEPTNO)
UNION
SELECT DEPT.DNAME, EMP.ENAME
FROM EMP RIGHT OUTER JOIN DEPT
ON (DEPT.DEPTNO = EMP.DEPTNO);

-- CARTESIAN JOIN
-- JOIN WITHOUT WHERE
SELECT DNAME, ENAME 
FROM EMP, DEPT;		-- FASTER
SELECT ENAME, DNAME
FROM DEPT, EMP;		-- SLOWER

-- SELF JOIN
SELECT A.ENAME, B.ENAME
FROM EMP AS B, EMP AS A
WHERE A.MGR = B.EMPNO;

CREATE TABLE DEPTHEAD(DEPTNO INT, DHAED VARCHAR(10));

ALTER TABLE DEPTHEAD CHANGE DHAED DHEAD VARCHAR(10);

INSERT INTO DEPTHEAD(DEPTNO, DHEAD)
VALUES	(1, 'ARUN'),
		(2, 'JACK');
        
-- JOINING 3 OR MORE TABLES
SELECT DNAME, ENAME, DHEAD 
FROM EMP, DEPT, DEPTHEAD
--   5     3      2
WHERE DEPTHEAD.DEPTNO = DEPT.DEPTNO AND DEPT.DEPTNO = EMP.DEPTNO;