USE EMPLOYEE;

SELECT ENAME 
FROM EMP
WHERE SAL = (SELECT MIN(SAL) FROM EMP);

SELECT * 
FROM EMP 
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'THOMAS');

DELETE FROM EMP
WHERE DEPTNO = (SELECT TEMPP.DEPTNO FROM (SELECT DEPTNO FROM EMP WHERE ENAME = 'THOMAS') AS TEMPP);

UPDATE EMP SET SAL = 10000
WHERE JOB = (SELECT TEMPP.JOB FROM (SELECT JOB FROM EMP WHERE ENAME = 'KIRUN') AS TEMPP);

-- MULTI ROW SUB-QUERIES
SELECT * 
FROM EMP 
WHERE SAL = ANY(SELECT SAL FROM EMP WHERE JOB = 'M');

-- ANY  => LOGICAL OR
-- IN   => LOGICAL OR
-- ALL  => LOGICAL AND

SELECT DEPTNO, SUM(SAL)
FROM EMP 
GROUP BY DEPTNO;

SELECT MAX(SUM_SAL)
FROM 
	(SELECT SUM(SAL) 
	 AS SUM_SAL 
     FROM EMP 
     GROUP BY DEPTNO)
AS TEMPP;

SELECT DNAME
FROM DEPT
WHERE DEPTNO = ANY(SELECT DISTINCT DEPTNO FROM EMP);

-- Whenever you have a join, along with DISTINCT, to make it work faster, use correlated sub-query (use the EXISTS 
-- operator) this is the exception when sub-query is faster than join 

SELECT DNAME FROM DEPT 
WHERE EXISTS (SELECT DEPTNO FROM EMP 
			  WHERE DEPT.DEPTNO = EMP.DEPTNO);